services:
  philo:
    build:
      context: .
      dockerfile: Dockerfile
    image: philo-race:latest
    container_name: philo-race
    working_dir: /work/philo
    volumes:
      - ../philo:/work/philo
    tty: true
    stdin_open: true
    command: /bin/bash
